Bootstrap: docker
From: nvidia/cuda:9.1-cudnn7-devel

%environment
	PATH="/usr/local/anaconda/bin:$PATH"

%post
    # install anaconda
    if [ ! -d /usr/local/anaconda ]; then
         wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
            -O ~/anaconda.sh && \
         bash ~/anaconda.sh -b -p /usr/local/anaconda && \
         rm ~/anaconda.sh
    fi
    # set anaconda path
    export PATH="/usr/local/anaconda/bin:$PATH"

    # install required packages
    conda install pip
    pip install paddlepaddle-gpu
    conda clean --tarballs

% runscript
	echo "Singularity: paddlepaddle"
	exec /bin/bash
