#!/bin/bash
#PBS -l select=1:ncpus=48:mpiprocs=48:ngpus=1
#PBS -A AFSNW27526A21
#PBS -q standard
#PBS -l walltime=24:00:00
#PBS -N rnn_translator_native
#PBS -V
#PBS -M mdeyoung@afit.edu
#PBS -m be

cd $PBS_O_WORKDIR

source ${MODULESHOME}/init/bash

module load cuda/9.1
module load cudnn/cuda9.0/7.4.2

# conda init bash
source ${HOME}/.bashrc

conda activate pytorch-gpu

export SOURCE_DIR="${HOME}/git/afit_mlperf_training/rnn_translator/pytorch"
. ${SOURCE_DIR}/run_and_time.sh
